### ISSUE TITLE
animations missing on footer

### ISSUE THREAD

**Issue by ripudamansinghthind** [ripudamansinghthind/portfolio-website#46]

**Comment by Sky-De** [comment]
@ripudamansinghthind After checking the live link, I noticed that the animation on the footer works but half of the footer is not visible on the screen

**take a look at it here**
![chrome-capture-2024-1-6 (1)](https://github.com/ripudamansinghthind/portfolio-website/assets/79264045/6a0f79bd-5a0d-45a4-b745-16af7eb40291)

If you assign this task to me, I can fix it. After that, we can discuss the lack of responsiveness (issue #45)

**Comment by ripudamansinghthind** [comment]
you are welcome to contribute. Assigned, thanks!

**Comment by ripudamansinghthind** [comment]
Update: fixed - closed
